<?php
define("TEMPLATE", -1);
define("GAME_ON", 0);
// SI CHANGEMENT DE NOM DE MISSION : RECHERCHER REMPLACER DANS TOUT LE DOCUMENT ^^

//Liste des noms des missions
//On les retrouve dans le fichier php_mission.php
define("MOT_DE_PASSE", 1);
define("MOT_DE_PASSE_OK", 2);
define("RDV_MOUTARDE", 3);
define("VIBRO1",4);
define("APPARITION",5);
define("GLORIETTES1",6);
define("GLORIETTES2",7);
define("GLORIETTES3",8);
define("GLORIETTES4",9);
define("ESPRIT01",10);
define("VIBRO2",11);
define("STATUE_EXVOTO",12);
define("ROSES",13);
define("ESPRIT02",14);
define("VIBRO3",15);
define("LAVOIR1", 16);
define("VIBRO4",17);
define("LAVOIR2",18);
define("VIBRO5",19);
define("DICK",20);
define("ESPRIT03",21);
define("VIBRO6", 22);
define("STATUE_FOND", 23);
define("STATUE_FOND_2", 24);
define("ESPRIT04",25);
define("REINE_ROI", 26);
define("REPRODUIRE_REINE", 27);
define("REPRODUIRE_ROI",28);
define("ESPRIT05",29);
define("VIBRO7",30);
define("STATUE_CENTRE",31);
define("STATUE_CENTRE_2",32);
define("ESPRIT06", 33);
define("ESPRIT_FIN",34);
define("FIN_DE_GAME",35);

// POUR LES CODES ET CODES D'ERREURS :
// $info_missions[NOM_MISSION][CODE] = ["code valide 1", "code valide 2", "code valide X"];
// $info_missions[NOM_MISSION][ERREUR_CODE] = [1=> "code faux 1", "code faux 2", ..... , "code faux x"];
// $info_missions[NOM_MISSION][VALIDATION_FAIL] = ["message par défaut", "message du code 1", "message du code 2", ......, "message du code x"];
// IL FAUT qu'il y ait un message pas défaut, plus un message par code d'erreur, sinon le système est cassé (j'ai pas fait de try catch pour l'instant)

/*Exemple de déclaration de mission
1. Mission standard = une image + un texte + une question + une réponse + des indices

2. Maintenant je veux une mission où on affiche du texte, qui a un point sur la map qui reste

*/

// info des missions, sous forme de tableau de tableaux.
$info_missions[TEMPLATE] =	[TITLE => "",		//S'affiche en haut sur la page de la mission
									DESC => "",
									CLUE => [],
									X => 0,
									Y => 0,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => [""],
									ERREUR_CODE => [],
									PLACEHOLDER => "",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 0,
									AFFICHER_FINISH_LIST => true, //Afficher dans la liste des missions résolues - après résolution hein
									AFFICHER_FINISH_MAP => false, //Afficher le point une fois la mission terminée 
									STANDARD => true,
									TYPE_CODE => CODE_STANDARD,
									MISSION_SUIVANTE => 0,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									MISSION_LINK_BUTTON_NAME => "", //Texte du bouton lien vers la mission d'après
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];

$info_missions[GAME_ON] = 	[TITLE => "", // TITRE DE LA MISSION
									DESC => "", // DESCRIPTION DE LA MISSION
									CLUE => [], // INDICE POUR FINIR LA MISSION
									X => "", // POSITION X SUR LA CARTE
									Y => "", // POSITION Y SUR LA CARTE
									HAS_CODE => false, // FAUT-IL SAISIR UN CODE POUR FINIR LA MISSION
									QUESTION => "",
									CODE => "", // CODE NECESSAIRE POUR FINIR LA MISSION
									WIN_TITLE => "", //Phrase qu'on ajoute dans la zone mission terminée
									CARTE => 0]; //Carte 0 ne pas afficher. 1 = 1650. 2 = 1750
									
$info_missions[MOT_DE_PASSE] =	[TITLE => "", //"Bienvenue"
									DESC => "<p class=\"text-mission\"><br>Bonjour bonjour, et bienvenue dans les Jardins du Prieuré. J'ai entendu dire que vous veniez enquêter sur les mystérieux murmures qui enchantent ce lieu ?</p><p class=\"text-mission\">Je sui<span style=\"color:#F4BC3C;\">s</span> le célèbre baro<span style=\"color:#38BBB2;\">n</span> Moutarde, ma réputation tient de mon amour des objets anciens et de l'histoire qu'ils racontent.</p><p class=\"text-mission\">Mon équipe de chercheurs vient de mettre a<span style=\"color:#B679B7;\">u</span> point un <b>Vibrophone</b> : Un objet unique et essentiel pour votre mission !<br>En parlant de mission, l'écureuil a un mot de passe pour moi, quel est-il ?</p>",
									CLUE => ["Hihi, je suis le premier indice de la partie, n'hésitez pas à consulter mes frères et soeurs indices lorsque vous en ressentirez le besoin pendant votre aventure. Nous sommes là pour vous aider et ça commence maintenant !<br>Observez l'enveloppe que vous avez entre les mains, si vous avez remarqué les 3 fleurs de couleur c'est que vous êtes sur la bonne voie.", "Suivez les petits écureuils pour trouver l'ordre.", "Avez vous remarqué les lettres en couleurs dans le blabla du baron Moutarde ?","Attention, le prochain indice vous donne la solution ! Chaque lettre a sa propre couleur, remettez les lettres dans le bon ordre grâce à l'écureuil et aux 3 fleurs sur l'enveloppe.","La solution est S orange, U violet, N bleu : SUN."],
									X => 38.5,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Mot de passe",
									CODE => ["9911","SUN"],
									ERREUR_CODE => [1=>""],
									PLACEHOLDER => "3 lettres",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => MOT_DE_PASSE_OK,
									VISUEL => "Moutarde.png",
									IMG_ALT => "Moutarde",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Oh non, je vous ai sûrement pris pour quelqu'un d'autre.<br>Vous êtes sûrs de ne pas avoir un mot de passe entre vos mains ?","Euh... Vous n'avez pas saisi de mot de passe... Huhu"],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[MOT_DE_PASSE_OK] =	[TITLE => "", //"Rencontre avec Moutarde"
									DESC => "<p class=\"text-mission\">Super ! Désolé pour ce contretemps mais l'équipe de Sergio rode et il serait tragique que notre vibrophone tombe entre de mauvaises mains.</p><p class=\"text-mission\">Si vous êtes un tantinet observateur vous aurez remarqué le bouton en haut de la page.<br>Ce bouton 'Carte' vous permet de consulter... la carte des jardins !</p><p class=\"text-couleur\">Je vous ai noté dessus notre prochain lieu de rendez vous. Cliquez sur le point une fois que penserez être à cet endroit.</p>",
									CLUE => [],
									X => 38.5,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => [""],
									ERREUR_CODE => [1=>""],
									WIN_TITLE => "Rencontre avec Moutarde",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => RDV_MOUTARDE,
									VISUEL => "Moutarde.png",
									IMG_ALT => "Moutarde",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[RDV_MOUTARDE] =	[TITLE => "", //"Rendez vous avec Moutarde"
									DESC => "<p class=\"text-mission\">Vous allez me demander pourquoi nous nous retrouvons ici ?<br>Eh bien la réponse est très simple.</p><p class=\"text-mission\">Voyez vous le gros bloc de pierre avec une phrase gravée dessus ?</p><p class=\"text-mission\">C'est à cet endroit que nous avons détecté les plus fortes vibrations.</p><p class=\"text-mission\">Grâce au vibrophone vous devriez réussir à entendre et comprendre les murmures<span style=\"color:#EBB121;\"> qui émanent de cette pierre.</span></p><p class=\"text-mission\">Pour ma part, je vous prie de bien vouloir m'excuser, je dois vous laisser.<br>Bonne chance.</p><p class=\"text-couleur\">Vous pouvez ouvrir l'enveloppe \"Rendez vous dans les jardins du Prieuré\", vous y trouverez le manuel d'utilisation du Vibrophone ainsi qu'un plan des jardins que je vous ai scotché dessus.</p>",
									CLUE => [],
									X => 69,
									Y => 25.5,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => ["9911"],
									ERREUR_CODE => [1=>"1111"],
									WIN_TITLE => "Rencontre avec le Vibrophone",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => VIBRO1,
									VISUEL => "Moutarde.png",
									IMG_ALT => "Moutarde",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => VIBRO1,
									MISSION_LINK_BUTTON_NAME => "Sortir le vibrophone",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Ce n'est pas ça. Regardez mieux ce coquinou"],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[VIBRO1] =	[TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Avez vous essayé de toucher les boutons ?<br>Commencez par trouver le bouton on.","Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est fort, placez l'aiguille dans la zone rouge.","Concernant les affineurs, vous cherchez à communiquer avec une pierre donc placez les sur 'Pierre' et 'Non genré'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Pour cette première utilisation, utilisez la vitesse 3.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 69,
									Y => 25.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["16344","17344","18344","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => APPARITION,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => APPARITION,
									MISSION_LINK_BUTTON_NAME => "Quelque chose est apparu",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "fort",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_FORT
									];
																		
$info_missions[APPARITION] =	[TITLE => "",//"Rencontre avec l'esprit",
									CLUE => [],
									DESC => "<p class=\"text-esprit\">Je suis l'esprit des Jardins du Prieuré<br>Puissiez vous entendre ma volonté</p><p class=\"text-esprit\">Non loin de moi une pierre est gravée<br>D'une phrase pour tous ces hommes tombés</p><p class=\"text-mission-center\">'Tout peuple qui oublie son passé<br>Se condamne à le revivre',</p><p class=\"text-esprit\">Mais elle évoque aussi mes plantes,<br>Un jour méfiantes, un jour flamboyantes</p><p class=\"text-esprit\">Arpentez mes lignes sans plus attendre<br>Avant que mes souvenirs ne redeviennent cendres.</p><p class=\"text-mission\">Cet esprit dit des trucs un peu bizarre, il semble qu'il souhaite que les Jardins du Prieuré existent et qu'ils ne retournent jamais dans l'oubli.</p><p class=\"text-couleur\">De nouveaux points viennent d'apparaitre sur la carte.</p>",
									X => 69,
									Y => 25.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => [],
									ERREUR_CODE => [],
									PLACEHOLDER => "",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => false,
									MISSION_SUIVANTE => 0,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit00",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[GLORIETTES1] =	[TITLE => "Nom oublié",
									DESC => "<p class=\"text-esprit\">Par ces quatre les gens passent,<br>Mais sans aucune attention,<br>Un symbole ça se chasse,<br>Il suffit de faire preuve d'observation.<br></p><p class=\"text-mission\">Comment se nomment ces 4 édifices métalliques ?</p>",
									CLUE => ["Chaque 'édifice métallique' cache 2 symboles, observez bien autour de vous.","Avez vous remarqué les symboles sur la carte que vous avez entre vos mains ?","Chaque symbole vous donne une lettre.", "Remplacez chaque symbole par la bonne lettre pour trouver le nom de ces édifices.", "Ces édifices sont appelés GLORIETTES !"],
									X => 27,
									Y => 50,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Nom",
									CODE => ["9911", "GLORIETTES","GLORIETTE"],
									ERREUR_CODE => [1=>"SORTILEGE"],
									VALIDATION_FAIL => ["Arf non ça ne me dit rien... Essayez encore peut être n'avez vous pas trouvé les 8 symboles.", "Les lettres sont bonnes mais ces structures ne s'appellent pas des Sortilèges !"],
									PLACEHOLDER => "XXXXXXXXXX",
									WIN_TITLE => "Retrouver le nom des édifices métalliques",
									WIN_DESC => "Vous savez maintenant qu'elles se nomment gloriettes. C'est mignon n'est ce pas ?",
									CARTE => 1,
									AFFICHER_FINISH_LIST => true,
									AFFICHER_FINISH_MAP => true,
									STANDARD => true,
									MISSION_SUIVANTE => ESPRIT01,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									MISSION_LINK_BUTTON_NAME => "",
									DISPLAY_VALIDATION_FAIL => true,
									DISPLAY_VALIDATION_SUCCESS => true,
									VALIDATION_SUCCESS => "ok",									
									];

$info_missions[GLORIETTES2] = $info_missions[GLORIETTES1];
$info_missions[GLORIETTES2][X] = 52.5;
$info_missions[GLORIETTES2][Y] = 50;

$info_missions[GLORIETTES3] = $info_missions[GLORIETTES1];
$info_missions[GLORIETTES3][X] = 27.5;
$info_missions[GLORIETTES3][Y] = 66.5;

$info_missions[GLORIETTES4] = $info_missions[GLORIETTES1];
$info_missions[GLORIETTES4][X] = 53;
$info_missions[GLORIETTES4][Y] = 67;

$info_missions[ESPRIT01] =	[TITLE => "L'Esprit des Jardins du Prieuré",
									DESC => "<p class=\"text-mission\">Oh merci, chaque souvenir que vous explorez<br>permet à mes couleurs de briller,<br>Mes couleurs sont mon essence,<br>Vous êtes ma dernière chance.</p>",
									CLUE => [""],
									X => 0,
									Y => 0,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => [""],
									ERREUR_CODE => [1=>"8781"],
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => 0,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS =>false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[VIBRO2] =	[TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est normal, placez l'aiguille dans la zone jaune.","Concernant les affineurs, vous cherchez à communiquer avec une statue féminine donc placez les sur 'Pierre' et 'Féminin'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Il semble que la vitesse 1 soit la mieux adaptée.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 63,
									Y => 19,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["14142","15142","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => STATUE_EXVOTO,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => STATUE_EXVOTO,
									MISSION_LINK_BUTTON_NAME => "Quelque chose nous parle",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "normal",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_NORMAL
									];
												
$info_missions[STATUE_EXVOTO] =	[TITLE => "Statue Ex Voto",
									DESC => "<p class=\"text-mission\">Enfin quelqu'un m'écoute !<br>Les Jardins du Prieuré ont vu naître une multitude de rosiers aux parfums riches et variés.<br>La Duchesse de Choiseul pouvait passer des heures à les admirer pousser et s'épanouir.</p><p class=\"text-couleur\">Un nouveau point a fait son apparition sur la carte.</p>",
									CLUE => [""],
									X => 63,
									Y => 19,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["8783", "87812", "9911"],
									ERREUR_CODE => [1=>'8781'],
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => true,
									MISSION_SUIVANTE => ROSES,
									VISUEL => "Vibrophone_petit.png",
									IMG_ALT => "Vibrophone",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[ROSES] =	[TITLE => "Les rosiers du Prieuré",
									DESC => (ROSIER_CRASH) ? "<p class=\"text-mission\">La duchesse adorait la poésie,<br>il y a plus d'un siècle ces vers elle écrivit,,<br>Elle se sentait inspiré,<br>Par ses trois rosiers préférés.</p><br><p class=\"text-mission-center\" style=\"color:lightblue;\">\"Il était un instant sans soleil,<br>Un moment de merveille,<br>Qui transforma la maisonnette des écureuils,<br>En construction de petites feuilles,<br>Mais le vieux Blush sortit une bougie,<br>Et mit fin à la magie.\"</p><br>C'est incroyable que les jardiniers les ai préservés, merci d'être venus les contempler." : "<p class=\"text-mission\">La Duchesse adorait la poésie,<br>il y a plus d'un siècle ces vers elle écrivit,<br>Elle se sentait inspiré,<br>Par ses trois rosiers préférés.</p><br><p class=\"text-mission-center\" style=\"color:lightblue;\">\"Il était un instant sans soleil,<br>Un moment de merveille,<br>Qui transforma la maisonnette des écureuils,<br>En construction de petites feuilles,<br>Mais le vieux Blush sortit une bougie,<br>Et mit fin à la magie.\"</p><br>Retrouvez les 3 rosiers préférés de la Duchesse !",
									CLUE => (ROSIER_CRASH) ? [] : ["Chaque vers fait référence à un rosier.","Le premier vers parle d'un instant sans soleil, comme une éclipse !", "Le 2nd vers parle d'écureuil, n'y a t il pas un rosier au nom de noisette ?","Haha, effectivement il y en a 2, peut être que le mot maisonnette n'est pas là par hasard.","Le dernier vers parle du vieux Blush ou old blush en anglais.","Saisissez les chiffres de chacun des rosiers, vous devriez en saisir 5.","Le code est 10811 !"],
									X => 30,
									Y => 41,
									GEANT => false,
									HAS_CODE => (ROSIER_CRASH) ? false : true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Les 3 rosiers :",
									CODE => ["10811","9911"],
									ERREUR_CODE => [1=>"10311"],
									PLACEHOLDER => "00000",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => true,
									MISSION_SUIVANTE => ESPRIT02,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => (ROSIER_CRASH) ? true : false,
									MISSION_LINK => (ROSIER_CRASH) ? ESPRIT02 : 0,
									MISSION_LINK_BUTTON_NAME => "On dirait que l'Esprit change !",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Non non non !","Vous n'êtes pas très loin, il y a 2 rosiers avec le mot noisette."],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bravo ! Cette machine redémarre enfin..."
									];
									
$info_missions[ESPRIT02] =	[TITLE => "L'Esprit des Jardins du Prieuré",
									DESC => "<p class=\"text-mission\">Spécial</p>",
									CLUE => [],
									X => 0,
									Y => 0,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "",
									CODE => ["0"],
									ERREUR_CODE => [1=>"1"],
									WIN_TITLE => "no title",
									WIN_DESC => "No Win desc",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => VIBRO3,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
//VIBRO3 Inutilisé !									
$info_missions[VIBRO3] = [TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est fort, placez l'aiguille dans la zone rouge.","Concernant les affineurs, vous cherchez à communiquer avec une statue féminine donc placez les sur 'Pierre' et 'Féminin'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Il semble que la vitesse 1 soit la mieux adaptée.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 25,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["16444","17444","18444","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => LAVOIR1,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => LAVOIR1,
									MISSION_LINK_BUTTON_NAME => "Quelque chose nous parle",
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "fort",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_FORT
									];

//LAVOIR1 Inutilisé !									
$info_missions[LAVOIR1] =	[TITLE => "Lavoir",
									DESC => "<p class=\"text-mission\">Splick, Bonjour, splock, j'aimerais beaucoup vous aider, splick, mais je ne suis pas du coin. Splock, il y a de cela qualques temps, splick, j'étais encore dans, splock, dans le ciel, splick, à chercher un endroit sympa à arroser. Splock, si vous cherchez à en apprendre, splick, d'avantage sur l'histoire de ce lieu, splock, je vous conseille de communiquer, splick, avec le lavoir, il n'a pas l'air tout jeune celui là ! Splock</p>",
									CLUE => [],
									X => 25,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => [""],
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => VIBRO4,
									VISUEL => "Vibrophone_petit.png",
									IMG_ALT => "Vibrophone",
									AUTOFINISH => true,
									HAS_MISSION_LINK => true,
									MISSION_LINK => VIBRO4,
									MISSION_LINK_BUTTON_NAME => "Retour au vibrophone",
									];
									
$info_missions[VIBRO4] =	[TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Peut être essayez vous de communiquer avec l'eau ? Elle ne semble pas répondre à votre appel.","Essayez plutôt de communiquer avec le lavoir","Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est fort, placez l'aiguille dans la zone rouge.","Concernant les affineurs, vous cherchez à communiquer avec un lavoir en pierre donc placez les sur 'Pierre' et 'Non genré'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Il semble que la vitesse 4 soit la mieux adaptée.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 25,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["16444","17444","18444","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => false,
									MISSION_SUIVANTE => LAVOIR2,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => LAVOIR2,
									MISSION_LINK_BUTTON_NAME => "Vous entendez ?",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "fort",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_FORT
									];
									
$info_missions[LAVOIR2] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Vous ! Humains !<br>Vous ne cessez de venir laver vos saletés sans jamais la moindre reconnaissance !<br>Pourquoaaaaaaaaaa !!<br>...<br>Oh?! C'est l'esprit des jardins qui vous envoie, vous n'êtes peut être pas si sauvage après tout.<br>Avez vous déjà entendu parler du petit chien adoré de la Duchesse de Choiseul ? Elle l'aimait tant... Il repose dans les Jardins, passez le voir ça lui fera plaisir.</p><p class=\"text-couleur\">Un nouveau point a fait son apparition sur la carte.</p>",
									CLUE => [""],
									X => 25,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => [""],
									ERREUR_CODE => [],
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => true,
									MISSION_SUIVANTE => VIBRO5,
									VISUEL => "Vibrophone_petit.png",
									IMG_ALT => "Vibrophone",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0
									];
									
$info_missions[VIBRO5] =	[TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Le lavoir nous avait parlé du chien de la Duchesse...","La souche ne semble pas répondre, cherchez autour il devrait y avoir une pierre pas loin.","Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est faible, placez l'aiguille dans la zone verte.","Concernant les affineurs, vous cherchez à communiquer avec un petit chien donc placez les sur 'Ossement' et 'Animal'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Il semble que la vitesse 5 soit la mieux adaptée.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 75,
									Y => 35,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["11533","12533","13533","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => true,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => DICK,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => DICK,
									MISSION_LINK_BUTTON_NAME => "On entend un chien ?!",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "faible",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_FAIBLE
									];
									
$info_missions[DICK] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Wouwou ! Est ce que wous auriez wu ma maîtresse ? Cela fait des années w'elle n'est pas wenuf me woir...  Waf, nous passions wouf notre temps ensemble à wourir dans les jardins. La Duchesse waimait la nature et les animauf, on arrive encore à lire mon nom wur la pierre dewant laquelle wouf wous trouwez, approchez wouf pour le retrouwer.</p>",
									CLUE => ["Son nom est sur la pierre, juste devant vous !","Ou derrière vous !","La pierre est vraiment toute proche","Il commence par DI et finit par CK","Arg ! Le précédent indice ne vous a pas suffit ?"],
									X => 75,
									Y => 35,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Comment se nommait le chien de la Duchesse ?",
									CODE => ["DICK","9911"],
									ERREUR_CODE => [1=>"10311"],
									PLACEHOLDER => "XXXX",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => true,
									MISSION_SUIVANTE => ESPRIT03,
									VISUEL => "Vibrophone_petit.png",
									IMG_ALT => "Vibrophone",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => ESPRIT03,
									MISSION_LINK_BUTTON_NAME => "Wouhaaa",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Désolé, ce n'est ça.", "Alors oui, il y a des tomates sur ses pizzas, mais... ce n'est pas son ingrédient fétiche !", "Alors oui, il y a des tomates sur ses pizzas, mais... ce n'est pas son ingrédient fétiche !"],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[ESPRIT03] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Nous devrions chercher un flyer de pizzeria par ici.</p>",
									CLUE => ["Le flyer qui nous intéresse est tout en haut à droite !","La solution est dans son slogan."],
									X => 75,
									Y => 35,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Quel ingrédient Stic met-il sur toutes ses pizzas ?",
									CODE => ["9911", "NOISETTE", "NOISETE", "NOISSETTE", "NOISSETE", "NOISETTES", "NOISETES", "NOISSETTES", "NOISSETES"],
									ERREUR_CODE =>[1=>"TOMATE", "TOMATES"],
									PLACEHOLDER => "Ingrédient",
									WIN_TITLE => "Trouver le flyer de la pizzeria",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => VIBRO6,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Désolé, ce n'est ça.", "Alors oui, il y a des tomates sur ses pizzas, mais... ce n'est pas son ingrédient fétiche !", "Alors oui, il y a des tomates sur ses pizzas, mais... ce n'est pas son ingrédient fétiche !"],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];

$info_missions[VIBRO6] =	[TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est faible, placez l'aiguille dans la zone verte.","Concernant les affineurs, vous cherchez à communiquer avec une statue féminine donc placez les sur 'pierre' et 'Féminin'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Il semble que la vitesse 2 soit la mieux adaptée.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 41,
									Y => 72,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["11242","12242","13242","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => STATUE_FOND,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => STATUE_FOND,
									MISSION_LINK_BUTTON_NAME => "Ça y est !",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "faible",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_FAIBLE
									];
									
$info_missions[STATUE_FOND] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Oh bonjour, bienvenue dans mon petit temple végétal, n'est il pas mignon ?<br>Il y a tout autour de nous une multitude d'arbres incroyables, saurez vous les retrouver ?</p><p class=\"text-couleur\">Vous pouvez ouvrir l'enveloppe 'Les racines de la nature'.<br>Trouvez chacun des arbres et indiquez son emplacement sur la carte. Revenez me voir lorque vous les aurez tous trouvé !<br><br>Attention !<br>Le premier arbre a été coupé, mais il reste tout à fait reconnaissable !</p>",
									CLUE => ["", "", "", "", ""],
									X => 41,
									Y => 72,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => 0,
									QUESTION => "",
									CODE => [],
									ERREUR_CODE => [1=>"", ""],
									PLACEHOLDER => "",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => STATUE_FOND_2,
									VISUEL => "Vibrophone_petit.png",
									IMG_ALT => "Vibrophone",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									MISSION_LINK_BUTTON_NAME => "",
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];

$info_missions[STATUE_FOND_2] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Voir mission_statue_fond</p>",
									CLUE => ["Il y a 15 zones où peuvent se trouver les 8 arbres que vous cherchez, cliquez sur une zone pour valider que vous avez trouvé un arbre à cet endroit, recliquez sur la zone pour indiquer que vous n'avez pas trouvé d'arbre à cet endroit."],
									X => 41,
									Y => 72,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => 0,
									QUESTION => "",
									CODE => ["KORN", "9911"],
									ERREUR_CODE => [1=>"QUEEN", "PINK FLOYD"],
									PLACEHOLDER => "Groupe de musique ?",
									WIN_TITLE => "",
									WIN_DESC => "Vous avez retrouvé le pizzaiolo. C'est cool.",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => ESPRIT04,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => ESPRIT04,
									MISSION_LINK_BUTTON_NAME => "L'esprit a gagné une couleur",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Décidement, cet écureuil est du genre casse-noisette !", "Ha... J'adore aussi, mais je pense qu'il préfère quelque chose de plus rythmé !", "It's just another squirrel on the wall ! Mais non..."],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];									
									
$info_missions[ESPRIT04] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Blabla</p>",
									CLUE => [],
									X => 41,
									Y => 72,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_COULEUR,
									SPEC_CODE => [" "," "," "," "," "," "],
									QUESTION => "",
									CODE => ["105"],
									ERREUR_CODE => [1=>"150", "015", "051", "510", "501"],
									PLACEHOLDER => "",
									WIN_TITLE => "Trouver Stac",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => false,
									MISSION_SUIVANTE => REINE_ROI,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Décidement, cet écureuil est du genre casse-noisette !", "Je crois que ce sont les bonnes couleurs, mais pas le bon ordre...", "Je crois que ce sont les bonnes couleurs, mais pas le bon ordre...", "Je crois que ce sont les bonnes couleurs, mais pas le bon ordre...", "Je crois que ce sont les bonnes couleurs, mais pas le bon ordre...", "Je crois que ce sont les bonnes couleurs, mais pas le bon ordre..."],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[REINE_ROI] =	[TITLE => "La Reine et le Roi",
									DESC => "<p class=\"text-esprit\">Jusqu'ici vous êtes arrivé,<br>à coté de l'échiquier vous avez dû passer,<br>mais avez vous remarqué,<br>la précision avec laquelle les arbres ont été taillés ?</p><br><br>Sauriez vous reproduire la Reine ?",
									CLUE => [],
									X => 53,
									Y => 65,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => "",
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => REPRODUIRE_REINE,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => REPRODUIRE_REINE,
									MISSION_LINK_BUTTON_NAME => "Lancer la reproduction"
									];

$info_missions[REPRODUIRE_REINE] =	[TITLE => "La Reine",
									DESC => "<p class=\"text-esprit\"></p>",
									CLUE => ["Si vous ne savez par où commencer, essayez de vous placer pile poil au centre du cercle sur la map","Si vous êtes au bon endroit vous devriez vous retrouver dans une de ces cages vertes dont je tairais le nom.","Observez bien ! Le dessin de la Reine n'est pas très loin.","Regardez le panneau d'information, tout en bas."],
									X => 53,
									Y => 65,
									GEANT => false,
									HAS_CODE => true,									
									QUESTION => "",
									CODE => ["475"],
									ERREUR_CODE => [1=>""],
									WIN_TITLE => "",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => 0,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => REPRODUIRE_ROI,
									MISSION_LINK_BUTTON_NAME => "Bravo !",
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[REPRODUIRE_ROI] =	[TITLE => "Le Roi",
									DESC => "<p class=\"text-mission\">Maintenant que vous êtes lancé, pourquoi ne pas reproduire le roi ?</p>",
									CLUE => ["Vous avez trouvé la Reine mais pas le roi ?","Retournez voir le dessin de la Reine, ils sont inséparables."],
									X => 53,
									Y => 65,
									GEANT => false,
									HAS_CODE => true,
									QUESTION => "",
									CODE => ["625"],
									ERREUR_CODE => [1=>""],
									WIN_TITLE => "Se rendre à 1750",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => 0,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => ESPRIT05,
									MISSION_LINK_BUTTON_NAME => "Bravo !",
									DISPLAY_VALIDATION_FAIL => false,
									VALIDATION_FAIL => [],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];

$info_missions[ESPRIT05] =	[TITLE => "Esprit",
									DESC => "<p class=\"text-mission\">Le Morse travaille au service de télécryptage en biophysique des particules de masse extra solaires...<br>Ce que je veux dire c'est qu'il se trouve généralement à son bureau à l'espace Wifi de l'office du tourisme.</p>",
									CLUE => ["Baissez légèrement les yeux pour l'apercevoir","Le code se cache dans le tableau derrière lui.","Prenez du recul sur le tableau pour voir les 3 chiffres.","Focalisez vous uniquement sur les montagnes.","Le 1er chiffre est un 3."],
									X => 53,
									Y => 65,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Code du morse",
									CODE => ["345", "9911"],
									ERREUR_CODE => [],
									PLACEHOLDER => "Chiffres",
									WIN_TITLE => "Trouver le Morse",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => false,
									MISSION_SUIVANTE => 0,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Non, ça n'est pas ça... Mais je vous fais confiance pour trouver."],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[VIBRO7] =	[TITLE => "Vibrophone",
									DESC => "",
									CLUE => ["Si vous entendez une sorte de buzzer c'est que vous n'avez pas trouvé comment régler correctement le fréquenceur et/ou les affineurs.","Le fréquenceur doit être réglé en fonction de la puissance du signal. Ici le signal est fort, placez l'aiguille dans la zone rouge.","Concernant les affineurs, vous cherchez à communiquer avec une statue féminine donc placez les sur 'pierre' et 'Féminin'","Si vous entendez quelque chose il ne vous reste plus qu'à trouver la bonne vitesse en jouant avec le modulateur de vitesse.","Il semble que la vitesse 3 soit la mieux adaptée.","Mince, vous avez tout ce qu'il faut pour trouver la solution. Reprenez tout depuis le début et cherchez ce qui pose problème."],
									X => 40.5,
									Y => 57.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => "",
									QUESTION => "",
									CODE => ["16342","17342","18342","11111"],
									ERREUR_CODE => [1=>"5829"],
									PLACEHOLDER => "",
									WIN_TITLE => "Rencontre avec l'esprit des Jardins du Prieuré",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => STATUE_CENTRE,
									VISUEL => "",
									IMG_ALT => "",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => STATUE_CENTRE,
									MISSION_LINK_BUTTON_NAME => "On entend quelque chose",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => [""],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => "Bien vu ! C'est ingénieux !",
									PUISSANCE_VIBRO => "fort",
									IMG_PUISSANCE_VIBRO => IMG_VIBRO_ECRAN_FORT
									];

$info_missions[STATUE_CENTRE] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Bonjour chers inconnus,<br>effectivement ma position n'est pour le moins pas des plus agréable hihihi mais c'est ainsi que m'a faite mon créateur alors je n'y peux rien ! hihihi.<br><br>J'étais en pleine réflexion : la mémoire ne cesse d'être mise à mal par le temps.<br>Et le temps passant, certains petits souvenirs changent peu à peu, perdent de leur éclat jusqu'à disparaitre dans un flou artistique d'ombres et de lumières jusqu'à ce que quelqu'un les ravive...<br><br>Alors que faire de ma position ? D'ici 2 minutes vous l'aurez oublié. hihihi.<br></p><p class=\"text-couleur\">J'ai un défi pour vous, voyons voir si votre mémoire vous permettra de dissiper les anomalies qui se sont glissées sur la carte. hihihi.<br>Revenez me voir lorsque ce sera fait.</p>",
									CLUE => [],
									X => 40.5,
									Y => 57.5,
									GEANT => false,
									HAS_CODE => false,
									QUESTION => "",
									CODE => "",
									WIN_TITLE => "Décryptage du morse effectué",
									WIN_DESC => "",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => true,
									MISSION_SUIVANTE => 0,
									VISUEL => "Vibrophone_petit.png",
									IMG_ALT => "Vibrophone",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => STATUE_CENTRE_2,
									MISSION_LINK_BUTTON_NAME => "Vous avez entendu ça ?"
									];

$info_missions[STATUE_CENTRE_2] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Voir mission_statue_centre</p>",
									CLUE => ["Identifiez les zones bleues et cliquez dessus pour rétablir la réalité."],
									X => 40.5,
									Y => 57.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => 0,
									QUESTION => "",
									CODE => ["KORN", "9911"],
									ERREUR_CODE => [1=>"QUEEN", "PINK FLOYD"],
									PLACEHOLDER => "Groupe de musique ?",
									WIN_TITLE => "",
									WIN_DESC => "Vous avez retrouvé le pizzaiolo. C'est cool.",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => ESPRIT06,
									VISUEL => SPECIAL_ESPRIT,
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => true,
									MISSION_LINK => ESPRIT06,
									MISSION_LINK_BUTTON_NAME => "Quelque chose est apparu",
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Décidement, cet écureuil est du genre casse-noisette !", "Ha... J'adore aussi, mais je pense qu'il préfère quelque chose de plus rythmé !", "It's just another squirrel on the wall ! Mais non..."],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];			
									
$info_missions[ESPRIT06] =	[TITLE => "Inspecter le bonhomme de neige",
									DESC => "Voir tableau_esprit",
									CLUE => ["No clue"],
									X => 40.5,
									Y => 57.5,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Code du bonhomme de neige",
									CODE => ["03H06","03h06","9911"],
									ERREUR_CODE => [],
									PLACEHOLDER => "Horaire",
									WIN_TITLE => "Trouver le Bonhomme de neige",
									WIN_DESC => "Ce bonhomme de neige est plutôt amusant, faut bien l'avouer. Maintenant, vous savez que Léo est passé par là hier à 03h06.",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => true,
									STANDARD => false,
									MISSION_SUIVANTE => ESPRIT_FIN,
									VISUEL => "Esprit.png",
									IMG_ALT => "Esprit",
									AUTOFINISH => true,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Code faux<br>Essayez encore ?"],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];
									
$info_missions[ESPRIT_FIN] =	[TITLE => "Inspecter le bonhomme de neige",
									DESC => "Voir tableau_esprit",
									CLUE => ["No clue"],
									X => 38.5,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => true,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "Code du bonhomme de neige",
									CODE => ["CDBBDD"],
									ERREUR_CODE => [],
									PLACEHOLDER => "Horaire",
									WIN_TITLE => "Trouver le Bonhomme de neige",
									WIN_DESC => "Ce bonhomme de neige est plutôt amusant, faut bien l'avouer. Maintenant, vous savez que Léo est passé par là hier à 03h06.",
									CARTE => 1,
									AFFICHER_FINISH_LIST => false,
									AFFICHER_FINISH_MAP => false,
									STANDARD => false,
									MISSION_SUIVANTE => FIN_DE_GAME,
									VISUEL => "Esprit.png",
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Code faux<br>Essayez encore ?"],
									DISPLAY_VALIDATION_SUCCESS => false,
									VALIDATION_SUCCESS => ""
									];

$info_missions[FIN_DE_GAME] =	[TITLE => "",
									DESC => "<p class=\"text-mission\">Merci d'avoir participé à la sauvegarde de la mémoire des jardins du Prieuré. Votre mission ne se termine pas ici, vous êtes les ambassadeurs de ce lieu et de toutes les merveilles qu'il renferme. Partagez autour de vous ce que vous avez découvert aujourd'hui.</p>",
									CLUE => [""],
									X => 38.5,
									Y => 29.5,
									GEANT => false,
									HAS_CODE => false,
									TYPE_CODE => CODE_STANDARD,
									QUESTION => "",
									CODE => [""],
									ERREUR_CODE => [],
									PLACEHOLDER => "4 Chiffres",
									WIN_TITLE => "Trouver la Boite aux lettres",
									WIN_DESC => "Boite aux lettre",
									CARTE => 1,
									AFFICHER_FINISH_LIST => true,
									AFFICHER_FINISH_MAP => true,
									STANDARD => false,									
									VISUEL => ESPRIT_FINAL,
									IMG_ALT => "Esprit",
									AUTOFINISH => false,
									HAS_MISSION_LINK => false,
									MISSION_LINK => 0,
									DISPLAY_VALIDATION_FAIL => true,
									VALIDATION_FAIL => ["Code faux !<br>Reprenons depuis le début... On descend, on va à droite etc..."],
									DISPLAY_VALIDATION_SUCCESS => true,
									VALIDATION_SUCCESS => "Bien vu ! En avant, allons trouver cet ours !"
									];
									
									
if (REDIRECT_AVIS) {
	$info_missions[FIN_DE_GAME][DESC] .= "<br><br><p class=\"text-mission\"><b>C'était une sacrée aventure ! Votre avis nous intéresse, <a href=\"".LIEN_AVIS."\">c'est ici que ça se passe !</a></b></p>";
}
?>